### ISSUE TITLE
connection refused

### ISSUE THREAD

**Issue by miyumiyuv** [rust3r/eth-brute#10]
-

**Comment by rust3r** [comment]
It's troubles with your rpc. Check configs

**Comment by onukanar** [comment]
all the configurations are correct and it works when I run it with go but not with docker unfortunately :/ t.me/xxavierss can you help me ?

**Comment by rust3r** [comment]
Sorry, I haven't tg. Maybe tox?

**Comment by onukanar** [comment]
add me please 151FF876D40365E0FAAA8367FFA112AECF1467D03F6B49561BAC5C8D3DED377F035E8B1AD346

**Comment by rust3r** [comment]
Added
