### ISSUE TITLE
some optional request !

### ISSUE THREAD

**Issue by Albertzan** [rust3r/eth-brute#13]
Hi @rust3r ,
can we have some options like : 
- on/off Total checks ( without reseting after restart soft ) 
- on/off verbose tree lines
- Address and Pk like this
Address: 0x8a9B71592caA83C303A99B46c57BAE9f8c784623  Balance : 0 Eth - 0 $/Eur
Secret: 52f0c2c77bcf7b1145ace3d52d01360e18ef379c540f5b974913f68bc97a44d2
- on/off verbose 
- color line changer
- weebhooks for discord
- balance converter from "0.44 ETH" to 'USD' 
- i want to learn coding ... i'm a noob .. and i'll be happy see this options ! :D

**Comment by aposhtol** [comment]
Hi! Also, does program only logs pk/address with 1+ ETH, not less?

**Comment by rust3r** [comment]
Hi! Nope
