### ISSUE TITLE
There are a verbose mode like -v for more details

### ISSUE THREAD

**Issue by rammos92** [rust3r/eth-brute#4]

**Comment by rammos92** [comment]
the best bruteforce isee until now it's yours , i have 2nd question about RPC , still working until ?? 
for details 
for exmple 
show address + PK + Bal

**Comment by rammos92** [comment]
another question you can add scan by Range for exmple 64 bit to 160 bit
Seq and random

**Comment by rust3r** [comment]
> the best bruteforce isee until now it's yours , i have 2nd question about RPC , still working until ?? for details for exmple show address + PK + Bal

Yes, you can use reserve servers from [source](https://github.com/rust3r/eth-brute/blob/main/main.go#L96)



> another question you can add scan by Range for exmple 64 bit to 160 bit Seq and random

I see if it possible
And will add verbose mode with more information

**Comment by rammos92** [comment]
any new about more details

**Comment by rust3r** [comment]
Sorry, haven't more details right now. I will try soon

**Comment by rust3r** [comment]
> the best bruteforce isee until now it's yours , i have 2nd question about RPC , still working until ?? for details for exmple show address + PK + Bal

added PK:address Bal
