### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Handsomekaizer** [rust3r/eth-brute#5]
Hello,
Please this script is not working, please can you upload to heroku or netlify to see if it works. I really need this thank you

**Comment by rust3r** [comment]
Hello! Can you try releases?

**Comment by Handsomekaizer** [comment]
I have released it on heroku but it does not work please can you try it

**Comment by rust3r** [comment]
Ok, i'm try

**Comment by rust3r** [comment]
I'm added heroku directive. You can try again. All works fine
